---
- hosts: windows

  vars_prompt:
    - name: host_name
      prompt: "Enter hostname that you would like to use"
      private: no

  tasks:
  - name: Change hostname to new name
    ansible.windows.win_hostname:
      name: "{{ host_name }}"
    register: res

  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required