---
- hosts: windows

  tasks:
  - name: Change hostname to ansible-dc
    ansible.windows.win_hostname:
      name: ansible-dc
    register: res

  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required