---
- hosts: windows

  tasks:
  - name: Copying PowerShell script to server
    win_copy:
      src: /home/parallels/ansible-windows/win_setipaddress/Set-IPWinServer.ps1
      dest: C:\Users\sysadmin\AppData\Local\Temp\Set-IPWinServer.ps1
  - name: Set DNS address on Ethernet 2 # Want to see if I can use Ansible to find active network interface
    win_dns_client:
      adapter_names: Ethernet 2
      ipv4_addresses: 10.0.0.4
